export default {
    env: 'development',
    longitude: -8.40,
    latitude: 43.40,
    topic: 'home/raspi/door',
    doorSensorGpio: 4,
    doorSensorPollInterval: 1000,
    ldrGpio: 17,
    ldrDarkRcTimeThreeshold: 1000,
    ldrRcTimeMaxValue: 1000000,
    ledOpenedGpio: 19,
    ledClosedGpio: 26,
    ledRequestSuccessGpio: 20,
    ledRequestErrorGpio: 21,
    ledBlinkDurationInMs: 100,
    ledBlinkTotalPeriodInMs: 2000,
    serverUrl: 'http://192.168.0.36:9000',
    basicAuthUsername: 'admin',
    basicAuthPassword: 'admin',
    username: 'admin',
    password: 'aA12345678&',
    debug: true,
    debugRequests: false
};