export default {
    env: process.env.NODE_ENV,
    longitude: parseFloat(process.env.RASPI_LONGITUDE),
    latitude: parseFloat(process.env.RASPI_LATITUDE),
    topic: process.env.RASPI_TOPIC,
    doorSensorGpio: parseInt(process.env.DOOR_SENSOR_GPIO),
    doorSensorPollInterval: parseInt(process.env.DOOR_SENSOR_POLL_INTERVAL),
    ldrGpio: parseInt(process.env.LDR_GPIO),
    ldrDarkRcTimeThreeshold: parseInt(process.env.LDR_DARK_RC_TIME_THREESHOLD),
    ldrRcTimeMaxValue: parseInt(process.env.LDR_RC_TIME_MAX_VALUE),
    ledOpenedGpio: parseInt(process.env.LED_OPENED_GPIO),
    ledClosedGpio: parseInt(process.env.LED_CLOSED_GPIO),
    ledRequestSuccessGpio: parseInt(process.env.LED_REQUEST_SUCCESS_GPIO),
    ledRequestErrorGpio: parseInt(process.env.LED_REQUEST_ERROR_GPIO),
    ledBlinkDurationInMs: parseInt(process.env.LED_BLINK_DURATION_IN_MS),
    ledBlinkTotalPeriodInMs: parseInt(process.env.LED_BLINK_TOTAL_IN_MS),
    serverUrl: process.env.IOT_SERVER_URL,
    basicAuthUsername: process.env.IOT_SERVER_BASIC_AUTH_USERNAME,
    basicAuthPassword: process.env.IOT_SERVER_BASIC_AUTH_PASSWORD,
    username: process.env.IOT_SERVER_USERNAME,
    password: process.env.IOT_SERVER_PASSWORD,
    debug: process.env.IOT_DEBUG,
    debugRequests: process.env.IOT_DEBUG_REQUESTS
};