export default {
  env: process.env.NODE_ENV,
  longitude: Number(process.env.RASPI_LONGITUDE),
  latitude: Number(process.env.RASPI_LATITUDE),
  topic: process.env.RASPI_TOPIC,
  doorSensorGpio: Number(process.env.DOOR_SENSOR_GPIO),
  doorSensorPollInterval: Number(process.env.DOOR_SENSOR_POLL_INTERVAL),
  ldrGpio: Number(process.env.LDR_GPIO),
  ldrDarkRcTimeThreeshold: Number(process.env.LDR_DARK_RC_TIME_THREESHOLD),
  ldrRcTimeMaxValue: Number(process.env.LDR_RC_TIME_MAX_VALUE),
  ledOpenedGpio: Number(process.env.LED_OPENED_GPIO),
  ledClosedGpio: Number(process.env.LED_CLOSED_GPIO),
  ledRequestSuccessGpio: Number(process.env.LED_REQUEST_SUCCESS_GPIO),
  ledRequestErrorGpio: Number(process.env.LED_REQUEST_ERROR_GPIO),
  ledBlinkDurationInMs: Number(process.env.LED_BLINK_DURATION_IN_MS),
  ledBlinkTotalPeriodInMs: Number(process.env.LED_BLINK_TOTAL_IN_MS),
  yeelightDeviceId: process.env.YEELIGHT_DEVICE_ID,
  yeelightBrightnessPercentage: process.env.YEELIGHT_BRIGHTNESS_PERCENTAGE,
  yeelightTransitionSpeedInMs: process.env.YEELIGHT_TRANSITION_SPEED_IN_MS,
  serverUrl: process.env.IOT_SERVER_URL,
  basicAuthUsername: process.env.IOT_SERVER_BASIC_AUTH_USERNAME,
  basicAuthPassword: process.env.IOT_SERVER_BASIC_AUTH_PASSWORD,
  username: process.env.IOT_SERVER_USERNAME,
  password: process.env.IOT_SERVER_PASSWORD,
  debug: process.env.IOT_DEBUG === "true",
  debugRequests: process.env.IOT_DEBUG_REQUESTS === "true",
};
